#!/bin/bash
#compton -cGC -e 0.8 -b
firefox -P default &
ssh-add &
sudo test_off.sh &

wicd-gtk &
zim &
terminator &
#nvidia-settings -a InitialPixmapPlacement=2 -a GlyphCache=1 -a PixmapCache=1 &
if [[ `xrandr -q |grep "LVDS-0 connected" |wc -l` = 1 ]]; then
	xrandr --output LVDS-0 --below DP-0
fi;

feh --bg-center /home/yed/private/img/bg/actual.png &
xscreensaver -nosplash &

tint2 &
xbindkeys &
dropbox &

